<?php
    define('DB_HOST','localhost');
    define('DB_USER','root');
    define('DB_PASS','');
    define('DB_NAME','test');
    define('USER_TABLE','users');
    define('TRACKER_TABLE','tracker');
    define('BLACKLIST_TABLE','blacklist');
?>